"""empty message

Revision ID: 20f36c65f77e
Revises: 62c8d3ac56b2
Create Date: 2024-08-19 23:46:57.904612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f36c65f77e'
down_revision = '62c8d3ac56b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('firstName',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               nullable=True)
        batch_op.alter_column('lastName',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('lastName',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('firstName',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
